[hugoVersion]
extended = true
min = "0.124.1"

# [[imports]]
# path = "github.com/zeon-studio/hugoplate"

[[imports]]
path = "../hugo-modules/search"

[[imports]]
path = "../hugo-modules/pwa"

[[imports]]
path = "../hugo-modules/images"

[[imports]]
path = "../hugo-modules/videos"

[[imports]]
path = "../hugo-modules/icons/font-awesome"

# [[imports]]
# path = "../hugo-modules/icons/themify-icons"

[[imports]]
path = "../hugo-modules/gzip-caching"

[[imports]]
path = "../hugo-modules/adsense"

[[imports]]
path = "../hugo-modules/accordion"

[[imports]]
path = "../hugo-modules/table-of-contents"

[[imports]]
path = "../hugo-modules/tab"

[[imports]]
path = "../hugo-modules/modal"

[[imports]]
path = "../hugo-modules/gallery-slider"

[[imports]]
path = "../hugo-modules/components/preloader"

[[imports]]
path = "../hugo-modules/components/social-share"

[[imports]]
path = "../hugo-modules/components/cookie-consent"

[[imports]]
path = "../hugo-modules/components/announcement"

[[imports]]
path = "../hugo-modules/components/custom-script"

[[imports]]
path = "../hugo-modules/components/render-link"

# [[imports]]
# path = "../hugo-modules/components/valine-comment"

# [[imports]]
# path = "../hugo-modules/components/crisp-chat"

[[imports]]
path = "../hugo-modules/shortcodes/button"

[[imports]]
path = "../hugo-modules/shortcodes/notice"

[[imports]]
path = "../hugo-modules/seo-tools/basic-seo"

[[imports]]
path = "../hugo-modules/seo-tools/site-verifications"

[[imports]]
path = "../hugo-modules/seo-tools/google-tag-manager"

[[imports]]
path = "../hugo-modules/seo-tools/baidu-analytics"

# [[imports]]
# path = "../hugo-modules/seo-tools/matomo-analytics"

# [[imports]]
# path = "../hugo-modules/seo-tools/plausible-analytics"

# [[imports]]
# path = "../hugo-modules/seo-tools/counter-analytics"

[[imports]]
path = "../hugo-modules/shortcodes/echarts"